Translations = {
    ["BR"] = loadstring(game:HttpGet("https://raw.githubusercontent.com/agenext/Translations/refs/heads/main/PT-BR.txt"))(),
    ["TH"] = {
		["994732206"] = {
			-- Others --
			["Social Media"] = "สื่อสังคมออนไลน์",
			["Farm"] = "ฟาร์ม",
			["Quests/Items"] = "ภารกิจ/ไอเท็ม",
			["Sea Events"] = "กิจกรรมทางทะเล",
			["Islands"] = "เกาะ",
			["Fruits/Raid"] = "ผลไม้/บุก",
			["Teleport"] = "เทเลพอร์ต",
			["Stats"] = "สถิติ",
			["Player"] = "ผู้เล่น",
			["Race"] = "เผ่า",
			["Shop"] = "ร้านค้า",
			["Visual"] = "ภาพ",
			["Misc"] = "เบ็ดเตล็ด",
			-- Social --
			["Someone Hub | Community"] = "Someone Hub | ชุมชน",
			["Join The Best Roblox Scripting Community"] = "เข้าร่วมชุมชนสคริปต์ Roblox ที่ดีที่สุด",
			["Someone Hub Official Channel"] = "Someone Hub ช่องทางทางการ",
			["Sign Up To Receive Updates About The Script As Soon As Possible."] = "สมัครเพื่อรับข่าวสารเกี่ยวกับสคริปต์โดยเร็วที่สุด",
			-- Misc --
			["Settings"] = "การตั้งค่า",
				["Select Weapon"] = "เลือกอาวุธ",
				["Select The Weapon That Will Be Used For General Farming"] = "เลือกอาวุธที่จะใช้สำหรับการฟาร์มทั่วไป",
				["Tween Speed"] = "ความเร็ว Tween",
				["Bring Enemies"] = "ดึงศัตรู",
				["Brings Enemies Close To Make Farming Easier"] = "ดึงศัตรูมาใกล้เพื่อให้ง่ายต่อการฟาร์ม",
				["Auto Buso Haki"] = "ออโต้บูโซฮาคิ",
				["Activates Buso Haki Whenever It Deactivates"] = "เปิดบูโซฮาคิทุกครั้งที่ปิด",
				["Auto Attack"] = "ออโต้โจมตี",
				["Attacks Nearby Players And Enemies"] = "โจมตีผู้เล่นและศัตรูที่อยู่ใกล้",
				["Activate V3"] = "เปิด V3",
				["Activates Race Ability V3 When Possible"] = "เปิดความสามารถเผ่า V3 เมื่อเป็นไปได้",
				["Enable V4"] = "เปิด V4",
				["Activates Race V4 Transformation When Charged"] = "เปิดการแปลงร่าง V4 ของเผ่าเมื่อชาร์จเต็ม",
			["Codes"] = "โค้ด",
				["Redeem Codes to Get Rewards"] = "แลกโค้ดเพื่อรับรางวัล",
			["Menus"] = "เมนู",
				["Open A Normal Fruit Shop"] = "เปิดร้านผลไม้ทั่วไป",
				["Open A Advanced Fruit Shop"] = "เปิดร้านผลไม้ขั้นสูง",
				["Open Titles Menu"] = "เปิดเมนูฉายา",
				["Open Valentine's Day Shop"] = "เปิดร้านวันวาเลนไทน์",
			["Team"] = "ทีม",
				["Join Pirates"] = "เข้าร่วมโจรสลัด",
				["Join Marines"] = "เข้าร่วมนาวิกโยธิน",
				["Choose Team"] = "เลือกทีม",
				["Time To Enter When Running The Script"] = "เวลาที่จะเข้าสู่เกมเมื่อรันสคริปต์",
				["Auto Choose Team"] = "เลือกทีมอัตโนมัติ",
				["Automatically Choose Your Team When You Enter The Game"] = "เลือกทีมอัตโนมัติเมื่อเข้าสู่เกม",
			["More FPS"] = "เพิ่ม FPS",
				["Remove Notifications"] = "ลบการแจ้งเตือน",
				["Removes All Notifications From Screen"] = "ลบการแจ้งเตือนทั้งหมดออกจากหน้าจอ",
				["Remove Damage"] = "ลบความเสียหาย",
				["Removes Damage Notifications Dropping From Enemies"] = "ลบข้อความดาเมจที่เด้งจากศัตรู",
				["FPS Boost"] = "บูสต์ FPS",
				["Remove A Number Of Things To Give An FPS Boost"] = "ลบหลายสิ่งเพื่อเพิ่ม FPS",
			["Others"] = "อื่น ๆ",
				["Send Allies"] = "ส่งพันธมิตร",
				["Sends And Accepts Allies To People"] = "ส่งและรับพันธมิตรกับทุกคนในเซิร์ฟเวอร์",
				["Auto Rejoin"] = "เข้าร่วมอัตโนมัติ",
				["Re-Enter When Kicked"] = "เข้าร่วมใหม่เมื่อถูกเตะ",
				["Auto Execute"] = "รันอัตโนมัติ",
				["Run The Script Every Time You Enter The Game"] = "รันสคริปต์ทุกครั้งที่คุณเข้าสู่เกม",
				["Reset Settings"] = "รีเซ็ตการตั้งค่า",
				["Reset Script Settings"] = "รีเซ็ตการตั้งค่าสคริปต์ทั้งหมด",
			-- Farm --
			["Chest"] = "หีบ",
			["Ectoplasm"] = "อีคโตพลาสซึม",
			["Bones"] = "กระดูก",
			["Eagle Boss"] = "บอสอินทรี",
			["Elite Hunters"] = "นักล่าชั้นยอด",
			["Bosses"] = "บอส",
			["Mastery"] = "ความชำนาญ",
			-- Quests --
			["Second Sea"] = "ทะเลที่สอง",
			["Third Sea"] = "ทะเลที่สาม",
			["Don Swan"] = "ดอนสวอน",
			["Bartilo Quest"] = "ภารกิจบาร์ติโล",
			["Citizen Quest"] = "ภารกิจชาวเมือง",
			["Law Boss"] = "บอสลอว์",
			["Barista Cousin"] = "ญาติบาริสต้า",
			["Berries"] = "เบอร์รี่",
			-- Sea Events --
			["Settings"] = "การตั้งค่า",
			-- Islands --
			["Kitsune Island"] = "เกาะคิทสึเนะ",
			["Mirage Island"] = "เกาะมายา",
			["Prehistoric Island"] = "เกาะก่อนประวัติศาสตร์",
			["Frozen Dimension"] = "มิติแช่แข็ง",
			-- Fruits --
			["Fruits"] = "ผลไม้",
			-- Teleport --
			["Seas"] = "ทะเล",
			-- Player --
			["Local Player"] = "ผู้เล่นของคุณ",
			["Aimbot Nearest"] = "เอมบอทใกล้สุด",
			["Target The Nearest Player"] = "เล็งผู้เล่นที่ใกล้ที่สุด",
			-- Race --
			["To Evolve"] = "วิวัฒนาการ",
			["Unlock Races"] = "ปลดล็อกเผ่า",
			-- Shop --
			["Christmas"] = "คริสต์มาส",
			["Valentine's Day"] = "วันวาเลนไทน์",
			["Ectoplasm"] = "อีคโตพลาสซึม",
			["Misc"] = "เบ็ดเตล็ด",
			["Fighting Styles"] = "สไตล์การต่อสู้",
			["Swords"] = "ดาบ",
			["Guns"] = "ปืน",
			["Accessories"] = "อุปกรณ์เสริม",
			["Races"] = "เผ่า",
			["Volcano Event"] = "กิจกรรมภูเขาไฟ",
			["Beast Hunter"] = "นักล่าสัตว์ร้าย",
			["Shark Hunter"] = "นักล่าฉลาม",
			["Dragon Talon Sage"] = "นักปราชญ์กรงเล็บมังกร",
			-- Visual --
			["Extra Sensory Perception"] = "การรับรู้พิเศษ",
				["Font Size"] = "ขนาดตัวอักษร",
				["Font Size To Be Used"] = "ขนาดตัวอักษรที่จะใช้",
				["Select Font"] = "เลือกฟอนต์",
				["Choose The Font That Will Be Used In The ESPs"] = "เลือกฟอนต์ที่จะใช้ใน ESP",
				["ESP Players"] = "ESP ผู้เล่น",
				["See Name, Distance, Health And Energy"] = "ดูชื่อ ระยะทาง พลังชีวิต และพลังงาน",
				["ESP Fruits"] = "ESP ผลไม้",
				["See Name And Distance"] = "ดูชื่อและระยะทาง",
				["ESP Berries"] = "ESP เบอร์รี่",
				["ESP Chests"] = "ESP หีบ",
				["ESP Islands"] = "ESP เกาะ",
				["ESP Flowers"] = "ESP ดอกไม้",
		},
	},
    ["VN"] = {
		["994732206"] = {
			-- Others --
		["Social Media"] = "Mạng Xã Hội",
		["Farm"] = "Farm",
		["Quests/Items"] = "Nhiệm Vụ/Vật Phẩm",
		["Sea Events"] = "Sự Kiện Biển",
		["Islands"] = "Đảo",
		["Fruits/Raid"] = "Trái Cây/Raid",
		["Teleport"] = "Dịch Chuyển",
		["Stats"] = "Chỉ Số",
		["Player"] = "Người Chơi",
		["Race"] = "Chủng Tộc",
		["Shop"] = "Cửa Hàng",
		["Visual"] = "Hình Ảnh",
		["Misc"] = "Khác",
		-- Social --
		["Someone Hub | Community"] = "Someone Hub | Cộng Đồng",
		["Join The Best Roblox Scripting Community"] = "Tham Gia Cộng Đồng Script Roblox Tốt Nhất",
		["Someone Hub Official Channel"] = "Someone Hub Kênh Chính Thức",
		["Sign Up To Receive Updates About The Script As Soon As Possible."] = "Đăng Ký Để Nhận Cập Nhật Về Script Sớm Nhất Có Thể",
		-- Misc --
		["Settings"] = "Cài Đặt",
			["Select Weapon"] = "Chọn Vũ Khí",
			["Select The Weapon That Will Be Used For General Farming"] = "Chọn Vũ Khí Sẽ Dùng Để Farm Chung",
			["Tween Speed"] = "Tốc Độ Tween",
			["Bring Enemies"] = "Kéo Kẻ Địch",
			["Brings Enemies Close To Make Farming Easier"] = "Kéo Kẻ Địch Lại Gần Để Farm Dễ Hơn",
			["Auto Buso Haki"] = "Tự Động Buso Haki",
			["Activates Buso Haki Whenever It Deactivates"] = "Kích Hoạt Buso Haki Khi Nó Bị Tắt",
			["Auto Attack"] = "Tự Động Tấn Công",
			["Attacks Nearby Players And Enemies"] = "Tấn Công Người Chơi Và Kẻ Địch Gần Đó",
			["Activate V3"] = "Kích Hoạt V3",
			["Activates Race Ability V3 When Possible"] = "Kích Hoạt Kỹ Năng V3 Của Chủng Tộc Khi Có Thể",
			["Enable V4"] = "Kích Hoạt V4",
			["Activates Race V4 Transformation When Charged"] = "Kích Hoạt Biến Hình V4 Của Chủng Tộc Khi Đủ",
		["Codes"] = "Mã Code",
			["Redeem Codes to Get Rewards"] = "Đổi Mã Để Nhận Phần Thưởng",
		["Menus"] = "Menu",
			["Open A Normal Fruit Shop"] = "Mở Cửa Hàng Trái Cây Thường",
			["Open A Advanced Fruit Shop"] = "Mở Cửa Hàng Trái Cây Cao Cấp",
			["Open Titles Menu"] = "Mở Menu Danh Hiệu",
			["Open Valentine's Day Shop"] = "Mở Cửa Hàng Ngày Lễ Tình Nhân",
		["Team"] = "Đội",
			["Join Pirates"] = "Tham Gia Hải Tặc",
			["Join Marines"] = "Tham Gia Hải Quân",
			["Choose Team"] = "Chọn Đội",
			["Time To Enter When Running The Script"] = "Thời Gian Vào Khi Chạy Script",
			["Auto Choose Team"] = "Tự Động Chọn Đội",
			["Automatically Choose Your Team When You Enter The Game"] = "Tự Động Chọn Đội Khi Vào Game",
		["More FPS"] = "Thêm FPS",
			["Remove Notifications"] = "Xóa Thông Báo",
			["Removes All Notifications From Screen"] = "Xóa Tất Cả Thông Báo Trên Màn Hình",
			["Remove Damage"] = "Xóa Sát Thương",
			["Removes Damage Notifications Dropping From Enemies"] = "Xóa Thông Báo Sát Thương Rơi Từ Kẻ Địch",
			["FPS Boost"] = "Tăng FPS",
			["Remove A Number Of Things To Give An FPS Boost"] = "Xóa Một Số Thứ Để Tăng FPS",
		["Others"] = "Khác",
			["Send Allies"] = "Gửi Đồng Minh",
			["Sends And Accepts Allies To People"] = "Gửi Và Nhận Đồng Minh Với Người Khác",
			["Auto Rejoin"] = "Tự Động Vào Lại",
			["Re-Enter When Kicked"] = "Vào Lại Khi Bị Đá",
			["Auto Execute"] = "Tự Động Chạy",
			["Run The Script Every Time You Enter The Game"] = "Chạy Script Mỗi Khi Vào Game",
			["Reset Settings"] = "Đặt Lại Cài Đặt",
			["Reset Script Settings"] = "Đặt Lại Tất Cả Cài Đặt Script",
		-- Farm --
		["Chest"] = "Rương",
		["Ectoplasm"] = "Ectoplasm",
		["Bones"] = "Xương",
		["Eagle Boss"] = "Boss Đại Bàng",
		["Elite Hunters"] = "Thợ Săn Tinh Anh",
		["Bosses"] = "Boss",
		["Mastery"] = "Thông Thạo",
		-- Quests --
		["Second Sea"] = "Biển Thứ Hai",
		["Third Sea"] = "Biển Thứ Ba",
		["Don Swan"] = "Don Swan",
		["Bartilo Quest"] = "Nhiệm Vụ Bartilo",
		["Citizen Quest"] = "Nhiệm Vụ Công Dân",
		["Law Boss"] = "Boss Law",
		["Barista Cousin"] = "Anh Họ Pha Chế",
		["Berries"] = "Quả Mọng",
		-- Sea Events --
		["Settings"] = "Cài Đặt",
		-- Islands --
		["Kitsune Island"] = "Đảo Kitsune",
		["Mirage Island"] = "Đảo Ảo Ảnh",
		["Prehistoric Island"] = "Đảo Tiền Sử",
		["Frozen Dimension"] = "Chiều Không Gian Băng Giá",
		-- Fruits --
		["Fruits"] = "Trái Cây",
		-- Teleport --
		["Seas"] = "Biển",
		-- Player --
		["Local Player"] = "Nhân Vật Của Bạn",
		["Aimbot Nearest"] = "Aimbot Gần Nhất",
		["Target The Nearest Player"] = "Ngắm Vào Người Chơi Gần Nhất",
		-- Race --
		["To Evolve"] = "Tiến Hóa",
		["Unlock Races"] = "Mở Khóa Chủng Tộc",
		-- Shop --
		["Christmas"] = "Giáng Sinh",
		["Valentine's Day"] = "Ngày Lễ Tình Nhân",
		["Ectoplasm"] = "Ectoplasm",
		["Misc"] = "Khác",
		["Fighting Styles"] = "Phong Cách Chiến Đấu",
		["Swords"] = "Kiếm",
		["Guns"] = "Súng",
		["Accessories"] = "Phụ Kiện",
		["Races"] = "Chủng Tộc",
		["Volcano Event"] = "Sự Kiện Núi Lửa",
		["Beast Hunter"] = "Thợ Săn Quái Thú",
		["Shark Hunter"] = "Thợ Săn Cá Mập",
		["Dragon Talon Sage"] = "Hiền Nhân Vuốt Rồng",
		-- Visual --
		["Extra Sensory Perception"] = "Nhận Thức Ngoại Cảm",
			["Font Size"] = "Kích Thước Chữ",
			["Font Size To Be Used"] = "Kích Thước Chữ Sẽ Dùng",
			["Select Font"] = "Chọn Phông Chữ",
			["Choose The Font That Will Be Used In The ESPs"] = "Chọn Phông Chữ Sẽ Dùng Trong ESP",
			["ESP Players"] = "ESP Người Chơi",
			["See Name, Distance, Health And Energy"] = "Xem Tên, Khoảng Cách, Máu Và Năng Lượng",
			["ESP Fruits"] = "ESP Trái Cây",
			["See Name And Distance"] = "Xem Tên Và Khoảng Cách",
			["ESP Berries"] = "ESP Quả Mọng",
			["ESP Chests"] = "ESP Rương",
			["ESP Islands"] = "ESP Đảo",
			["ESP Flowers"] = "ESP Hoa",
		},
	},
}